commit 27876596b5b0f55649c48abba387f5d405d1ce02
Author: Martin Vidner <mvidner@suse.cz>
Date:   Wed Dec 19 11:25:11 2012 +0100

    call va_end *before* potentially throwing an exception
    
    spotted by aschnell
    
    C99: "Each invocation of the va_start and va_copy macros shall be
    matched by a corresponding invocation of the va_end macro in the
    samed function." (7.15.1), quoted in
    http://stackoverflow.com/questions/11645282/do-i-need-to-va-end-when-an-exception-is-thrown

diff --git a/agent-ini/src/IniParser.cc b/agent-ini/src/IniParser.cc
index 56981c9f..4001272a 100644
--- a/agent-ini/src/IniParser.cc
+++ b/agent-ini/src/IniParser.cc
@@ -1032,8 +1032,9 @@ std::string format (const char * format, ...) {
 
     va_list ap;
     va_start( ap, format );
-
     int numprinted = vasprintf(&buf, format, ap);
+    va_end( ap );
+
     if (numprinted >= 0) {
         val = buf;
         free( buf );
@@ -1042,7 +1043,6 @@ std::string format (const char * format, ...) {
         throw std::runtime_error("vasprintf failed in ag_ini. Out of memory?");
     }
 
-    va_end( ap );
     return val;
 }
 

